name: Test Dockerfile

on:
  workflow_dispatch:
  workflow_call:

env:
  DOCKER_REGISTRY_URL: ghcr.io

permissions:
  contents: read
  packages: read

jobs:
  run-dockerfile-action-fails:
    name: Dockerfile (Fails)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: a-magdy/test-gh-docker-actions/test-gh-docker/dockerfile@main

  run-dockerfile-action-succeeds:
    name: Dockerfile (Succeeds)
    runs-on: ubuntu-latest
    needs: run-dockerfile-action-fails
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - name: Run Dockerfile Action
        uses: ./test-gh-docker/dockerfile
